### ISSUE TITLE
Link to realease page is invalid

### ISSUE THREAD

**Issue by pprados** [Fantom-Factory/projectBuilderPlus#1]
The link RELEASES https://github.com/Fantom-Factory/projectBuilderPlus/blob/master/Fantom-Factory/projectBuilderPlus/releases is broken

**Comment by SlimerDude** [comment]
Hi, thanks for reporting - you mean the link in the `readme.md` yeah?

I think it was a hold over from when the project was on BitBucket, but none-the-less, I've updated it to an absolute URL.

Cheers!
